### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by gardar** [maxhoesel/ansible-collection-caddy#5]
Hi.

Any chance for adding python 2 backwards compatibility?

I know python2 has been EOL officially now for a while, but it's still being supported by redhat and the ansible execution environment I'm  trying to use the collection in  (Redhat satellite). is stuck on ansible 2.9 and python 2.7 and I think Ansible Tower is faced with a similar issue.

**Comment by maxhoesel** [comment]
Hi! To be frank, supporting Python 2 in this collection is something that I'm not really interested in, mostly because 

- I don't have a use case for it personally
- It would require a fair bit of testing to make sure everything runs on both py2 and py3
- Doing so would mean converting the modules to a legacy codebase that would need to be changed back again once the Ansible team deprecates Python 2.7 support in a few years from now.

That said, I know that a lot of people are still using it one way or another and I'd like for people to be able to use this collection on those older systems, if possible. The good news is that most of the modules in this collection should be fairly straightforward to make compatible - most of the Python3-only features in there are things like f-strings and syntactic sugar. So if someone wants to put in the required work and make a py2 fork, I'd be happy to help if there are any issues.

**Comment by gardar** [comment]
Hi.
I absolutely understand that, and I wish I wouldn't have to bother with python 2 myself, it just seems to get more troublesome to be using python2 as the world moves on.

At first I thought the issue would just be running the modules from a ansible "controller" host that has python 2, but when I dug into it I found out that there are also issues with target hosts that have python 2,  which basically means that currently any distro that defaults to python 2 is a no-go.


I did a quick attempt at making the modules python2 compatible while retaining python3 compatibility, see #6 

So far `caddy_config` seems to work but `caddy_load` and `caddy_config_info` both fail with with a invalid syntax error on python 2. `Unable to import maxhoesel.caddy.caddy_config_info due to invalid syntax`
I can't figure out what syntax errors it's complaining about, validating the files with python gives no complaints and it seems to pass ansible-test, previously ansible-test did pick up other syntax errors that I fixed.
Any ideas what could be wrong?
